const FOLDER_TYPES = {
  GET_FOLDER_STARTED: 'GET_FOLDER_STARTED',
  GET_FOLDER_SUCCESS: 'GET_FOLDER_SUCCESS',
  GET_FOLDER_ERROR: 'GET_FOLDER_ERROR',
  GET_FOLDER_TEAM_STARTED: 'GET_FOLDER_TEAM_STARTED',
  GET_FOLDER_TEAM_SUCCESS: 'GET_FOLDER_TEAM_SUCCESS',
  GET_FOLDER_TEAM_ERROR: 'GET_FOLDER_TEAM_ERROR',
  SELECT_FOLDER: 'SELECT_FOLDER',
  EDIT_FOLDER_STARTED: 'EDIT_FOLDER_STARTED',
  EDIT_FOLDER_ERROR: 'EDIT_FOLDER_ERROR',
  DELETE_FOLDER_STARTED: 'DELETE_FOLDER_STARTED',
  DELETE_FOLDER_ERROR: 'DELETE_FOLDER_ERROR',
  CREATE_FOLDER_STARTED: 'CREATE_FOLDER_STARTED',
  CREATE_FOLDER_ERROR: 'CREATE_FOLDER_ERROR',
};

export default FOLDER_TYPES;
