const FOLDER_TYPES = {
  GET_FOLDER_STARTED: 'GET_FOLDER_STARTED',
  GET_FOLDER_SUCCESS: 'GET_FOLDER_SUCCESS',
  GET_FOLDER_ERROR: 'GET_FOLDER_ERROR',
  GET_FOLDER_TEAM_STARTED: 'GET_FOLDER_TEAM_STARTED',
  GET_FOLDER_TEAM_SUCCESS: 'GET_FOLDER_TEAM_SUCCESS',
  GET_FOLDER_TEAM_ERROR: 'GET_FOLDER_TEAM_ERROR',
  SELECT_FOLDER: 'SELECT_FOLDER',
};

export default FOLDER_TYPES;
