const MEMBERSHIP_TYPES = {
  GET_MEMBERSHIP_STARTED: 'GET_MEMBERSHIP_STARTED',
  GET_MEMBERSHIP_SUCCESS: 'GET_MEMBERSHIP_SUCCESS',
  GET_MEMBERSHIP_ERROR: 'GET_MEMBERSHIP_ERROR',
  UPDATE_MEMBERSHIP_STARTED: 'UPDATE_MEMBERSHIP_STARTED',
  UPDATE_MEMBERSHIP_ERROR: 'UPDATE_MEMBERSHIP_ERROR',
  CREATE_MEMBERSHIP_STARTED: 'CREATE_MEMBERSHIP_STARTED',
  CREATE_MEMBERSHIP_ERROR: 'CREATE_MEMBERSHIP_ERROR',
  DELETE_MEMBERSHIP_STARTED: 'DELETE_MEMBERSHIP_STARTED',
  DELETE_MEMBERSHIP_ERROR: 'DELETE_MEMBERSHIP_ERROR',
};

export default MEMBERSHIP_TYPES;
