const SPACE_TYPES = {
  ADD_SPACE_STARTED: 'ADD_SPACE_STARTED',
  ADD_SPACE_ERROR: 'ADD_SPACE_ERROR',
  EDIT_SPACE_STARTED: 'EDIT_SPACE_STARTED',
  EDIT_SPACE_ERROR: 'EDIT_SPACE_ERROR',
  DELETE_SPACE_STARTED: 'DELETE_SPACE_STARTED',
  DELETE_SPACE_ERROR: 'DELETE_SPACE_ERROR',
  GET_SPACE_NAVIGATION_STARTED: 'GET_SPACE_NAVIGATION_STARTED',
  GET_SPACE_NAVIGATION_SUCCESS: 'GET_SPACE_NAVIGATION_SUCCESS',
  GET_SPACE_NAVIGATION_ERROR: 'GET_SPACE_NAVIGATION_ERROR'
};

export default SPACE_TYPES;
