const TASK_TYPES = {
  GET_TASK_STARTED: 'GET_TASK_STARTED',
  GET_TASK_SUCCESS: 'GET_TASK_SUCCESS',
  GET_TASK_ERROR: 'GET_TASK_ERROR',
  GET_TASK_BY_ID_STARTED: 'GET_TASK_BY_ID_STARTED',
  GET_TASK_BY_ID_SUCCESS: 'GET_TASK_BY_ID_SUCCESS',
  GET_TASK_BY_ID_ERROR: 'GET_TASK_BY_ID_ERROR',
  EDIT_TASK_STARTED: 'EDIT_TASK_STARTED',
  EDIT_TASK_ERROR: 'EDIT_TASK_ERROR',
  CREATE_TASK_STARTED: 'CREATE_TASK_STARTED',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',
  DELETE_TASK_STARTED: 'DELETE_TASK_STARTED',
  DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',
};

export default TASK_TYPES;
