const TEAM_TYPES = {
  GET_TEAMS_STARTED: 'GET_TEAMS_STARTED',
  GET_TEAMS_SUCCESS: 'GET_TEAMS_SUCCESS',
  GET_TEAMS_ERROR: 'GET_TEAMS_ERRORS',
  ADD_TEAM_STARTED: 'ADD_TEAM_STARTED',
  ADD_TEAM_SUCCESS: 'ADD_TEAM_SUCCESS',
  ADD_TEAM_ERROR: 'ADD_TEAM_ERROR',
  EDIT_TEAM_STARTED: 'EDIT_TEAM_STARTED',
  EDIT_TEAM_SUCCESS: 'EDIT_TEAM_SUCCESS',
  EDIT_TEAM_ERROR: 'EDIT_TEAM_ERROR',
  DELETE_TEAM_STARTED: 'DELETE_TEAM_STARTED',
  DELETE_TEAM_SUCCESS: 'DELETE_TEAM_SUCCESS',
  DELETE_TEAM_ERROR: 'DELETE_TEAM_ERROR',
  LEAVE_TEAM_STARTED: 'LEAVE_TEAM_STARTED',
  LEAVE_TEAM_ERROR: 'LEAVE_TEAM_ERROR',
};

export default TEAM_TYPES;
