const USER_TYPES = {
    GET_USER_DETAILS_STARTED: 'GET_USER_DETAILS_STARTED',
    GET_USER_DETAILS_ERROR: 'GET_USER_DETAILS_ERROR',
    GET_USER_DETAILS_SUCCESS: 'GET_USER_DETAILS_SUCCESS',
}

export default USER_TYPES